# Generated by Django 6.0.5 on 2026-08-14 20:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_visualizacaocampanha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_entradas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_saidas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('receita_bruta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_comissoes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('resultado_operacional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('margem_operacional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_mensais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('ano', 'mes'), name='unique_fechamento_mensal')],
            },
        ),
    ]
