# Generated by Django 6.0.5 on 2026-08-14 21:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_fechamentomensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentomensal',
            name='pacientes_atendidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='procedimentos_realizados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='resultado_apos_custos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='ticket_medio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
