# Generated by Django 6.0.5 on 2026-08-15 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_fechamentomensal_pacientes_atendidos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='posicao_dente',
            field=models.CharField(choices=[('normal', 'Normal'), ('incluso_vertical', 'Inclusão vertical'), ('incluso_horizontal', 'Inclusão horizontal'), ('incluso_mesial', 'Inclusão mesial'), ('incluso_distal', 'Inclusão distal'), ('inclinado_direita', 'Inclinado para direita'), ('inclinado_esquerda', 'Inclinado para esquerda'), ('rotacao', 'Rotação / Giro'), ('extrusao', 'Extrusão')], default='normal', max_length=30),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='ano',
            field=models.PositiveIntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='mes',
            field=models.PositiveIntegerField(verbose_name='Mês'),
        ),
        migrations.AddIndex(
            model_name='fechamentomensal',
            index=models.Index(fields=['ano', 'mes'], name='idx_fechamento_ano_mes'),
        ),
        migrations.AddIndex(
            model_name='fechamentomensal',
            index=models.Index(fields=['status'], name='idx_fechamento_status'),
        ),
    ]
