# Generated by Django 6.0.5 on 2026-08-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_itemorcamento_posicao_dente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorcamento',
            name='posicao_dente',
        ),
        migrations.CreateModel(
            name='PosicionamentoDente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente', models.CharField(max_length=2)),
                ('posicao', models.CharField(choices=[('normal', 'Normal'), ('incluso_vertical', 'Inclusão vertical'), ('incluso_horizontal', 'Inclusão horizontal'), ('incluso_mesial', 'Inclusão mesial'), ('incluso_distal', 'Inclusão distal'), ('inclinado_direita', 'Inclinado para direita'), ('inclinado_esquerda', 'Inclinado para esquerda'), ('rotacao', 'Rotação / Giro'), ('extrusao', 'Extrusão')], default='normal', max_length=30)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicionamentos_dentes', to='accounts.paciente')),
            ],
            options={
                'verbose_name': 'Posicionamento do Dente',
                'verbose_name_plural': 'Posicionamentos dos Dentes',
                'constraints': [models.UniqueConstraint(fields=('paciente', 'dente'), name='unique_posicionamento_dente_paciente')],
            },
        ),
    ]
